### ISSUE TITLE
improvements to glyph validation groups

### ISSUE THREAD

**Issue by gferreira2** [gferreira/xTools4#11]
this is about the color-coded glyph validation groups used by GlyphValidator and GlyphSetProofer

- glyphs with same contours and different width appear as equal (blue) – should be white (contours only, different)
- empty glyphs currently appear together with contours only – should they be in their own groups? (empty equal / empty different)

**Comment by gferreira** [comment]
done in 24330215f8e583bce1258bead163f5ba06a490b9 and 9dd135ec8b5711b1592eb0ff26fbe28dc6dc1af1
